<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121200546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, interval_km INT DEFAULT NULL, interval_days INT DEFAULT NULL, absolute_due_odometer_km INT DEFAULT NULL, absolute_due_at DATE DEFAULT NULL, soon_km INT NOT NULL, soon_days INT NOT NULL, is_active BOOLEAN NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1319EF91545317D1 ON service_plan (vehicle_id)');
        $this->addSql('ALTER TABLE service_plan ADD CONSTRAINT FK_1319EF91545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_event ADD service_plan_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE service_event ADD CONSTRAINT FK_92DCE740271D5007 FOREIGN KEY (service_plan_id) REFERENCES service_plan (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_92DCE740271D5007 ON service_event (service_plan_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service_plan DROP CONSTRAINT FK_1319EF91545317D1');
        $this->addSql('DROP TABLE service_plan');
        $this->addSql('ALTER TABLE service_event DROP CONSTRAINT FK_92DCE740271D5007');
        $this->addSql('DROP INDEX IDX_92DCE740271D5007');
        $this->addSql('ALTER TABLE service_event DROP service_plan_id');
    }
}
