<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260205121618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dept_vehicle_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand VARCHAR(100) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, department_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F439000FAE80F5DF ON dept_vehicle_slot (department_id)');
        $this->addSql('CREATE INDEX IDX_F439000FC54C8C93 ON dept_vehicle_slot (type_id)');
        $this->addSql('ALTER TABLE dept_vehicle_slot ADD CONSTRAINT FK_F439000FAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dept_vehicle_slot ADD CONSTRAINT FK_F439000FC54C8C93 FOREIGN KEY (type_id) REFERENCES vehicle_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD staff_slot_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486553062A FOREIGN KEY (staff_slot_id) REFERENCES dept_vehicle_slot (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B80E486553062A ON vehicle (staff_slot_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dept_vehicle_slot DROP CONSTRAINT FK_F439000FAE80F5DF');
        $this->addSql('ALTER TABLE dept_vehicle_slot DROP CONSTRAINT FK_F439000FC54C8C93');
        $this->addSql('DROP TABLE dept_vehicle_slot');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E486553062A');
        $this->addSql('DROP INDEX UNIQ_1B80E486553062A');
        $this->addSql('ALTER TABLE vehicle DROP staff_slot_id');
    }
}
