<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121143650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(12, 3) NOT NULL, unit_cost NUMERIC(12, 4) DEFAULT NULL, lot_code VARCHAR(80) DEFAULT NULL, expiry_date DATE DEFAULT NULL, notes TEXT DEFAULT NULL, purchase_id INT NOT NULL, item_id INT NOT NULL, warehouse_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A1A77C95558FBEB9 ON purchase_line (purchase_id)');
        $this->addSql('CREATE INDEX IDX_A1A77C95126F525E ON purchase_line (item_id)');
        $this->addSql('CREATE INDEX IDX_A1A77C955080ECDE ON purchase_line (warehouse_id)');
        $this->addSql('ALTER TABLE purchase_line ADD CONSTRAINT FK_A1A77C95558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_line ADD CONSTRAINT FK_A1A77C95126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_line ADD CONSTRAINT FK_A1A77C955080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase_line DROP CONSTRAINT FK_A1A77C95558FBEB9');
        $this->addSql('ALTER TABLE purchase_line DROP CONSTRAINT FK_A1A77C95126F525E');
        $this->addSql('ALTER TABLE purchase_line DROP CONSTRAINT FK_A1A77C955080ECDE');
        $this->addSql('DROP TABLE purchase_line');
    }
}
