<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122135500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service_plan_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, interval_km INT DEFAULT NULL, interval_days INT DEFAULT NULL, absolute_due_odometer_km INT DEFAULT NULL, absolute_due_at DATE DEFAULT NULL, soon_km INT NOT NULL, soon_days INT NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service_plan_template_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, interval_km INT DEFAULT NULL, interval_days INT DEFAULT NULL, soon_km INT DEFAULT NULL, soon_days INT DEFAULT NULL, template_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F62DC455DA0FB8 ON service_plan_template_task (template_id)');
        $this->addSql('ALTER TABLE service_plan_template_task ADD CONSTRAINT FK_7F62DC455DA0FB8 FOREIGN KEY (template_id) REFERENCES service_plan_template (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service_plan_template_task DROP CONSTRAINT FK_7F62DC455DA0FB8');
        $this->addSql('DROP TABLE service_plan_template');
        $this->addSql('DROP TABLE service_plan_template_task');
    }
}
