<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260208104708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE part_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, note TEXT DEFAULT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BBCB7894AE80F5DF ON part_request (department_id)');
        $this->addSql('CREATE TABLE part_request_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, line_no INT NOT NULL, name_raw VARCHAR(255) NOT NULL, category VARCHAR(80) DEFAULT NULL, qty INT NOT NULL, comment TEXT DEFAULT NULL, request_id INT NOT NULL, vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52F85274427EB8A5 ON part_request_item (request_id)');
        $this->addSql('CREATE INDEX IDX_52F85274545317D1 ON part_request_item (vehicle_id)');
        $this->addSql('ALTER TABLE part_request ADD CONSTRAINT FK_BBCB7894AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE part_request_item ADD CONSTRAINT FK_52F85274427EB8A5 FOREIGN KEY (request_id) REFERENCES part_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE part_request_item ADD CONSTRAINT FK_52F85274545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE SET NULL NOT DEFERRABLE');
//        $this->addSql('DROP INDEX uniq_va_active_vehicle');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE part_request DROP CONSTRAINT FK_BBCB7894AE80F5DF');
        $this->addSql('ALTER TABLE part_request_item DROP CONSTRAINT FK_52F85274427EB8A5');
        $this->addSql('ALTER TABLE part_request_item DROP CONSTRAINT FK_52F85274545317D1');
        $this->addSql('DROP TABLE part_request');
        $this->addSql('DROP TABLE part_request_item');
        $this->addSql('CREATE UNIQUE INDEX uniq_va_active_vehicle ON vehicle_assignment (vehicle_id) WHERE (is_active = true)');
    }
}
