<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120143638 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vin VARCHAR(64) DEFAULT NULL, plate VARCHAR(32) DEFAULT NULL, make VARCHAR(80) DEFAULT NULL, model VARCHAR(80) DEFAULT NULL, year SMALLINT DEFAULT NULL, current_odometer_rm INT DEFAULT NULL, current_engine_hours NUMERIC(10, 2) DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE vehicle');
    }
}
