<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210095110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
//        $this->addSql('CREATE TABLE purchase_part_request (purchase_id INT NOT NULL, part_request_id INT NOT NULL, PRIMARY KEY (purchase_id, part_request_id))');
//        $this->addSql('CREATE INDEX IDX_7FD18F34558FBEB9 ON purchase_part_request (purchase_id)');
//        $this->addSql('CREATE INDEX IDX_7FD18F34770B3D61 ON purchase_part_request (part_request_id)');
//        $this->addSql('CREATE TABLE purchase_line_req_item_alloc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(12, 3) NOT NULL, purchase_line_id INT NOT NULL, request_item_id INT NOT NULL, PRIMARY KEY (id))');
//        $this->addSql('CREATE INDEX idx_alloc_line ON purchase_line_req_item_alloc (purchase_line_id)');
//        $this->addSql('CREATE INDEX idx_alloc_req_item ON purchase_line_req_item_alloc (request_item_id)');
//        $this->addSql('ALTER TABLE purchase_part_request ADD CONSTRAINT FK_7FD18F34558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) ON DELETE CASCADE');
//        $this->addSql('ALTER TABLE purchase_part_request ADD CONSTRAINT FK_7FD18F34770B3D61 FOREIGN KEY (part_request_id) REFERENCES part_request (id) ON DELETE CASCADE');
//        $this->addSql('ALTER TABLE purchase_line_req_item_alloc ADD CONSTRAINT FK_98C45A7D56A1BF3B FOREIGN KEY (purchase_line_id) REFERENCES purchase_line (id) ON DELETE CASCADE NOT DEFERRABLE');
//        $this->addSql('ALTER TABLE purchase_line_req_item_alloc ADD CONSTRAINT FK_98C45A7D384B2009 FOREIGN KEY (request_item_id) REFERENCES part_request_item (id) ON DELETE CASCADE NOT DEFERRABLE');
//        $this->addSql('ALTER TABLE doc DROP CONSTRAINT fk_8641fd64d19302f8');
//        $this->addSql('ALTER TABLE doc ADD purchase_id INT DEFAULT NULL');
//        $this->addSql('ALTER TABLE doc ALTER assignment_id DROP NOT NULL');
//        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64D19302F8 FOREIGN KEY (assignment_id) REFERENCES vehicle_assignment (id) ON DELETE SET NULL NOT DEFERRABLE');
//        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) ON DELETE CASCADE NOT DEFERRABLE');
//        $this->addSql('CREATE INDEX IDX_8641FD64558FBEB9 ON doc (purchase_id)');
//        $this->addSql('ALTER TABLE part_request_item ADD received_qty NUMERIC(12, 3) DEFAULT \'0.000\' NOT NULL');
//        $this->addSql('ALTER TABLE part_request_item ALTER qty TYPE NUMERIC(12, 3)');
//        $this->addSql('ALTER TABLE purchase ADD status VARCHAR(20) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
//        $this->addSql('ALTER TABLE purchase_part_request DROP CONSTRAINT FK_7FD18F34558FBEB9');
//        $this->addSql('ALTER TABLE purchase_part_request DROP CONSTRAINT FK_7FD18F34770B3D61');
//        $this->addSql('ALTER TABLE purchase_line_req_item_alloc DROP CONSTRAINT FK_98C45A7D56A1BF3B');
//        $this->addSql('ALTER TABLE purchase_line_req_item_alloc DROP CONSTRAINT FK_98C45A7D384B2009');
//        $this->addSql('DROP TABLE purchase_part_request');
//        $this->addSql('DROP TABLE purchase_line_req_item_alloc');
//        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64D19302F8');
//        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64558FBEB9');
//        $this->addSql('DROP INDEX IDX_8641FD64558FBEB9');
//        $this->addSql('ALTER TABLE doc DROP purchase_id');
//        $this->addSql('ALTER TABLE doc ALTER assignment_id SET NOT NULL');
//        $this->addSql('ALTER TABLE doc ADD CONSTRAINT fk_8641fd64d19302f8 FOREIGN KEY (assignment_id) REFERENCES vehicle_assignment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
//        $this->addSql('ALTER TABLE part_request_item DROP received_qty');
//        $this->addSql('ALTER TABLE part_request_item ALTER qty TYPE INT');
//        $this->addSql('ALTER TABLE purchase DROP status');
    }
}
