<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121143347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, purchase_date DATE NOT NULL, invoice_number VARCHAR(80) DEFAULT NULL, currency VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, supplier_id INT DEFAULT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6117D13B2ADD6D8C ON purchase (supplier_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B5080ECDE ON purchase (warehouse_id)');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B2ADD6D8C');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B5080ECDE');
        $this->addSql('DROP TABLE purchase');
    }
}
