<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121121025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_date DATE NOT NULL, odometer_km INT NOT NULL, engine_hours NUMERIC(10, 2) DEFAULT NULL, title VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, labor_cost NUMERIC(12, 2) DEFAULT NULL, other_cost NUMERIC(12, 2) DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92DCE740545317D1 ON service_event (vehicle_id)');
        $this->addSql('CREATE TABLE service_event_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty_used NUMERIC(12, 3) NOT NULL, unit_cost_snapshot NUMERIC(12, 4) DEFAULT NULL, notes TEXT DEFAULT NULL, service_event_id INT NOT NULL, warehouse_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_968150018881B3B6 ON service_event_item (service_event_id)');
        $this->addSql('CREATE INDEX IDX_968150015080ECDE ON service_event_item (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_96815001126F525E ON service_event_item (item_id)');
        $this->addSql('ALTER TABLE service_event ADD CONSTRAINT FK_92DCE740545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_event_item ADD CONSTRAINT FK_968150018881B3B6 FOREIGN KEY (service_event_id) REFERENCES service_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_event_item ADD CONSTRAINT FK_968150015080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_event_item ADD CONSTRAINT FK_96815001126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service_event DROP CONSTRAINT FK_92DCE740545317D1');
        $this->addSql('ALTER TABLE service_event_item DROP CONSTRAINT FK_968150018881B3B6');
        $this->addSql('ALTER TABLE service_event_item DROP CONSTRAINT FK_968150015080ECDE');
        $this->addSql('ALTER TABLE service_event_item DROP CONSTRAINT FK_96815001126F525E');
        $this->addSql('DROP TABLE service_event');
        $this->addSql('DROP TABLE service_event_item');
    }
}
