<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260205115836 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vehicle_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE4364755E237E06 ON vehicle_type (name)');
        $this->addSql('ALTER TABLE department ADD parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A727ACA70 FOREIGN KEY (parent_id) REFERENCES department (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CD1DE18A727ACA70 ON department (parent_id)');
        $this->addSql('ALTER TABLE vehicle ADD type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486C54C8C93 FOREIGN KEY (type_id) REFERENCES vehicle_type (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_1B80E486C54C8C93 ON vehicle (type_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE vehicle_type');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A727ACA70');
        $this->addSql('DROP INDEX IDX_CD1DE18A727ACA70');
        $this->addSql('ALTER TABLE department DROP parent_id');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E486C54C8C93');
        $this->addSql('DROP INDEX IDX_1B80E486C54C8C93');
        $this->addSql('ALTER TABLE vehicle DROP type_id');
    }
}
