<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206125429 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE doc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, doc_number VARCHAR(64) DEFAULT NULL, doc_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_name VARCHAR(255) DEFAULT NULL, file_size INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type_id INT NOT NULL, assignment_id INT NOT NULL, vehicle_id INT DEFAULT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8641FD64C54C8C93 ON doc (type_id)');
        $this->addSql('CREATE INDEX IDX_8641FD64D19302F8 ON doc (assignment_id)');
        $this->addSql('CREATE INDEX IDX_8641FD64545317D1 ON doc (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_8641FD64AE80F5DF ON doc (department_id)');
        $this->addSql('CREATE INDEX idx_doc_created_at ON doc (created_at)');
        $this->addSql('CREATE TABLE doc_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5C4E0FF77153098 ON doc_type (code)');
        $this->addSql('CREATE TABLE vehicle_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, note TEXT DEFAULT NULL, vehicle_id INT NOT NULL, department_id INT NOT NULL, staff_slot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B557CB27545317D1 ON vehicle_assignment (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_B557CB27AE80F5DF ON vehicle_assignment (department_id)');
        $this->addSql('CREATE INDEX IDX_B557CB27553062A ON vehicle_assignment (staff_slot_id)');
        $this->addSql('CREATE INDEX idx_va_is_active ON vehicle_assignment (is_active)');
        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64C54C8C93 FOREIGN KEY (type_id) REFERENCES doc_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64D19302F8 FOREIGN KEY (assignment_id) REFERENCES vehicle_assignment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc ADD CONSTRAINT FK_8641FD64AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_assignment ADD CONSTRAINT FK_B557CB27545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_assignment ADD CONSTRAINT FK_B557CB27AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_assignment ADD CONSTRAINT FK_B557CB27553062A FOREIGN KEY (staff_slot_id) REFERENCES dept_vehicle_slot (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql("CREATE UNIQUE INDEX uniq_va_active_vehicle ON vehicle_assignment (vehicle_id) WHERE is_active = true");

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64C54C8C93');
        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64D19302F8');
        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64545317D1');
        $this->addSql('ALTER TABLE doc DROP CONSTRAINT FK_8641FD64AE80F5DF');
        $this->addSql('ALTER TABLE vehicle_assignment DROP CONSTRAINT FK_B557CB27545317D1');
        $this->addSql('ALTER TABLE vehicle_assignment DROP CONSTRAINT FK_B557CB27AE80F5DF');
        $this->addSql('ALTER TABLE vehicle_assignment DROP CONSTRAINT FK_B557CB27553062A');
        $this->addSql('DROP TABLE doc');
        $this->addSql('DROP TABLE doc_type');
        $this->addSql('DROP TABLE vehicle_assignment');
        $this->addSql("DROP INDEX IF EXISTS uniq_va_active_vehicle");

    }
}
