<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121211254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service_event_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, interval_km INT DEFAULT NULL, interval_days INT DEFAULT NULL, soon_km INT NOT NULL, soon_days INT NOT NULL, status VARCHAR(20) NOT NULL, done_odometer_km INT DEFAULT NULL, done_date DATE DEFAULT NULL, service_event_id INT NOT NULL, plan_task_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DBE4AE3A8881B3B6 ON service_event_task (service_event_id)');
        $this->addSql('CREATE INDEX IDX_DBE4AE3A3309498E ON service_event_task (plan_task_id)');
        $this->addSql('CREATE TABLE service_plan_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, interval_km INT DEFAULT NULL, interval_days INT DEFAULT NULL, soon_km INT DEFAULT NULL, soon_days INT DEFAULT NULL, sort_order INT NOT NULL, service_plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F392D9D271D5007 ON service_plan_task (service_plan_id)');
        $this->addSql('ALTER TABLE service_event_task ADD CONSTRAINT FK_DBE4AE3A8881B3B6 FOREIGN KEY (service_event_id) REFERENCES service_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_event_task ADD CONSTRAINT FK_DBE4AE3A3309498E FOREIGN KEY (plan_task_id) REFERENCES service_plan_task (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_plan_task ADD CONSTRAINT FK_1F392D9D271D5007 FOREIGN KEY (service_plan_id) REFERENCES service_plan (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service_event_task DROP CONSTRAINT FK_DBE4AE3A8881B3B6');
        $this->addSql('ALTER TABLE service_event_task DROP CONSTRAINT FK_DBE4AE3A3309498E');
        $this->addSql('ALTER TABLE service_plan_task DROP CONSTRAINT FK_1F392D9D271D5007');
        $this->addSql('DROP TABLE service_event_task');
        $this->addSql('DROP TABLE service_plan_task');
    }
}
