<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260523190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create vehicle_image table for vehicle photos linked to odometer/date/document events.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE IF NOT EXISTS vehicle_image (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_id INT NOT NULL,
    document_id INT DEFAULT NULL,
    event_date DATE DEFAULT NULL,
    odometer_km INT DEFAULT NULL,
    title VARCHAR(160) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    file_name VARCHAR(255) DEFAULT NULL,
    file_size INT DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY(id)
)
SQL);
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_vehicle_image_vehicle ON vehicle_image (vehicle_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_vehicle_image_document ON vehicle_image (document_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_vehicle_image_event_date ON vehicle_image (event_date)');
        $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_vehicle_image_vehicle'
          AND t.relname = 'vehicle_image'
    ) THEN
        ALTER TABLE vehicle_image
            ADD CONSTRAINT fk_vehicle_image_vehicle
            FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE c.conname = 'fk_vehicle_image_document'
          AND t.relname = 'vehicle_image'
    ) THEN
        ALTER TABLE vehicle_image
            ADD CONSTRAINT fk_vehicle_image_document
            FOREIGN KEY (document_id) REFERENCES doc (id)
            ON DELETE SET NULL;
    END IF;
END $$;
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS vehicle_image');
    }
}
