<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121125436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventory_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, е�type VARCHAR(32) NOT NULL, qty_change NUMERIC(12, 3) NOT NULL, unit_cost NUMERIC(12, 4) DEFAULT NULL, ref_type VARCHAR(40) DEFAULT NULL, ref_id BIGINT DEFAULT NULL, note TEXT DEFAULT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, warehouse_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C5391E5080ECDE ON inventory_transaction (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_6C5391E126F525E ON inventory_transaction (item_id)');
        $this->addSql('ALTER TABLE inventory_transaction ADD CONSTRAINT FK_6C5391E5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_transaction ADD CONSTRAINT FK_6C5391E126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory_transaction DROP CONSTRAINT FK_6C5391E5080ECDE');
        $this->addSql('ALTER TABLE inventory_transaction DROP CONSTRAINT FK_6C5391E126F525E');
        $this->addSql('DROP TABLE inventory_transaction');
    }
}
